name: todoey
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # FireBase Packages
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  cloud_firestore: ^4.3.1
  firebase_storage: ^11.0.11
  firebase_messaging: ^14.2.2
  firebase_analytics: ^10.1.1
  google_sign_in: ^5.4.4
  flutter_facebook_auth: ^5.0.7

  # BloC Package
  flutter_bloc: ^8.1.2

  # Helper Packages
  http: ^0.13.5
  shared_preferences: ^2.0.17
  intl: ^0.17.0
  workmanager: ^0.5.1


  # UI Packages
  day_night_time_picker: ^1.1.5
  modal_progress_hud_nsn: ^0.3.0
  fluttertoast: ^8.1.1
  image_picker: ^0.8.6

  # Animation Packages
  animated_text_kit: ^4.2.2
  flutter_spinkit: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # -------------------- Add Assets Section --------------------
  assets:
    - assets/images/

  fonts:
    - family: BrokenIcons
      fonts:
        - asset: assets/broken-icons/BrokenIcons.ttf

    - family: Horizon-Personal
      fonts:
        - asset: assets/fonts/Horizon-PersonalUse.otf